apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
        use epoll;
        worker_connections 128;
    }
    error_log /var/log/nginx-error.log info;
    http {
      server_tokens off;
      include mime.types;
      default_type application/octet-stream;
      charset utf-8;
      access_log /var/log/nginx-access.log combined;
      server {
        server_name localhost;
        listen 80;
        location / {
            root /var/www/html;
            index index.html index.htm;
            }
       }
      server {
        listen 8080;
        server_name localhost;
        location = /basic_status {
          stub_status;
        }
      }
    }
