apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  type: ClusterIP
  ports:
    - name: exporter
      port: 9113
      protocol: TCP
      targetPort: 9113
